DELIMITER $$
CREATE PROCEDURE DeleteOldAds()
BEGIN
    DELETE FROM ad WHERE date_created <= DATE_SUB(NOW(), INTERVAL 30 DAY);
    -- SELECT * FROM ad WHERE date_created <= DATE_SUB(NOW(), INTERVAL 10 DAY);
END

$$

DELIMITER ;

CREATE EVENT `execDeleteOldAds`
	-- ON SCHEDULE EVERY 1 DAY
	ON SCHEDULE EVERY 5 SECOND
	STARTS '2013-11-13 00:00:00'
	ON COMPLETION NOT PRESERVE ENABLE
	DO call DeleteOldAds;

SET GLOBAL event_scheduler = ON;